export default {
	"vue/no-multi-spaces":                           "warn",
	"vue/no-spaces-around-equal-signs-in-attribute": "warn",
	"vue/multiline-html-element-content-newline":    "warn",
	"vue/html-closing-bracket-newline":              "warn",
	"vue/html-closing-bracket-spacing":              "warn",
	"vue/html-quotes":                               "warn",
	"vue/mustache-interpolation-spacing":            "warn",
	"vue/singleline-html-element-content-newline":   "warn",
	"vue/array-bracket-spacing":                     "warn",
	"vue/arrow-spacing":                             "warn",
	"vue/block-spacing":                             "warn",
	"vue/brace-style":                               "warn",
	"vue/camelcase":                                 "warn",
	"vue/comma-dangle":                              "warn",
	"vue/eqeqeq":                                    "error",
	"vue/key-spacing":                               "warn",
	"vue/no-boolean-default":                        "warn",
	"vue/no-restricted-syntax":                      "warn",
	"vue/require-direct-export":                     "warn",
	"vue/space-infix-ops":                           "warn",
	"vue/space-unary-ops":                           "warn",
	"vue/html-indent":                               [
		"error",
		"tab",
		{
			attribute:                 1,
			baseIndent:                1,
			closeBracket:              0,
			alignAttributesVertically: true,
			ignores:                   [],
		},
	],
	"vue/max-attributes-per-line": [ "error", { singleline: { max: 4 }, multiline: { max: 1 } } ],
};