export const studentsNotifications = [
  {
    id:          "15614",
    name:        "João Silva",
    description: "Concluiu a tarefa",
    date:        "2024-11-01",
    type:        "Info",
  },
  {
    id:          "21084",
    name:        "Ana Souza",
    description: "Faltou à aula",
    date:        "2024-11-02",
    type:        "Aviso",
  },
  {
    id:          "33571",
    name:        "Carlos Oliveira",
    description: "Precisa melhorar as notas",
    date:        "2024-11-03",
    type:        "Aviso",
  },
  {
    id:          "42349",
    name:        "Lucas Pereira",
    description: "Recebeu feedback positivo",
    date:        "2024-11-04",
    type:        "Info",
  },
  {
    id:          "53456",
    name:        "Mariana Gomes",
    description: "Faltou à prova final",
    date:        "2024-11-05",
    type:        "Urgente",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Completou todos os exercícios",
    date:        "2024-11-06",
    type:        "Info",
  },
  {
    id:          "21084",
    name:        "Ana Souza",
    description: "Fez melhorias no projeto",
    date:        "2024-11-07",
    type:        "Info",
  },
  {
    id:          "33571",
    name:        "Carlos Oliveira",
    description: "Reprovado na avaliação final",
    date:        "2024-11-08",
    type:        "Urgente",
  },
  {
    id:          "42349",
    name:        "Lucas Pereira",
    description: "Entrega de trabalho atrasada",
    date:        "2024-11-09",
    type:        "Aviso",
  },
  {
    id:          "53456",
    name:        "Mariana Gomes",
    description: "Ficou de recuperação",
    date:        "2024-11-10",
    type:        "Urgente",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Precisa de mais atenção no conteúdo",
    date:        "2024-11-11",
    type:        "Aviso",
  },
  {
    id:          "21084",
    name:        "Ana Souza",
    description: "Participou de todas as aulas este mês",
    date:        "2024-11-12",
    type:        "Info",
  },
  {
    id:          "33571",
    name:        "Carlos Oliveira",
    description: "Entrega atrasada no trabalho final",
    date:        "2024-11-13",
    type:        "Aviso",
  },
  {
    id:          "42349",
    name:        "Lucas Pereira",
    description: "Fez um excelente progresso na disciplina",
    date:        "2024-11-14",
    type:        "Info",
  },
  {
    id:          "53456",
    name:        "Mariana Gomes",
    description: "Foi elogiada pelo desempenho",
    date:        "2024-11-15",
    type:        "Info",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Recebeu feedback positivo dos professores",
    date:        "2024-11-16",
    type:        "Info",
  },
  {
    id:          "21084",
    name:        "Ana Souza",
    description: "Contribuiu no projeto em grupo",
    date:        "2024-11-17",
    type:        "Aviso",
  },
  {
    id:          "33571",
    name:        "Carlos Oliveira",
    description: "Notificação sobre comportamento",
    date:        "2024-11-18",
    type:        "Urgente",
  },
  {
    id:          "42349",
    name:        "Lucas Pereira",
    description: "Apresentou um ótimo projeto",
    date:        "2024-11-19",
    type:        "Info",
  },
  {
    id:          "53456",
    name:        "Mariana Gomes",
    description: "Atrasou o envio da redação final",
    date:        "2024-11-20",
    type:        "Aviso",
  },
];

export const studentNotifications = [
  {
    id:          "15614",
    name:        "João Silva",
    description: "Concluiu a tarefa",
    date:        "2024-11-01",
    type:        "Info",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Faltou à aula",
    date:        "2024-11-02",
    type:        "Aviso",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Recebeu feedback positivo dos professores",
    date:        "2024-11-03",
    type:        "Info",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Precisa melhorar as notas",
    date:        "2024-11-04",
    type:        "Aviso",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Foi elogiado pelo desempenho",
    date:        "2024-11-05",
    type:        "Info",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Faltou à prova final",
    date:        "2024-11-06",
    type:        "Urgente",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Completou todos os exercícios",
    date:        "2024-11-07",
    type:        "Info",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Reprovado na avaliação final",
    date:        "2024-11-08",
    type:        "Urgente",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Fez melhorias no projeto",
    date:        "2024-11-09",
    type:        "Info",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Ficou de recuperação",
    date:        "2024-11-10",
    type:        "Urgente",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Precisa de mais atenção no conteúdo",
    date:        "2024-11-11",
    type:        "Aviso",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Recebeu um excelente feedback dos colegas",
    date:        "2024-11-12",
    type:        "Info",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Entrega atrasada no trabalho final",
    date:        "2024-11-13",
    type:        "Aviso",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Foi elogiado pela participação ativa em aula",
    date:        "2024-11-14",
    type:        "Info",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Atrasou o envio da redação final",
    date:        "2024-11-15",
    type:        "Aviso",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Apresentou um ótimo projeto",
    date:        "2024-11-16",
    type:        "Info",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Faltou ao último encontro do grupo",
    date:        "2024-11-17",
    type:        "Aviso",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Demonstrou interesse em aprender mais",
    date:        "2024-11-18",
    type:        "Info",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Teve comportamento inadequado em aula",
    date:        "2024-11-19",
    type:        "Urgente",
  },
  {
    id:          "15614",
    name:        "João Silva",
    description: "Recebeu elogios por trabalho em equipe",
    date:        "2024-11-20",
    type:        "Info",
  },
];

export const notificationTableColumns = [ {
  key:   "id",
  label: "Matricula",
}, {
  key:      "name",
  label:    "Nome do Aluno",
  sortable: true,
}, {
  key:   "description",
  label: "Descrição",
}, {
  key:      "date",
  label:    "Data",
  sortable: true,
}, {
  key:      "type",
  label:    "Tipo",
  sortable: true,
} ];