export const studentNotifications = [
  { id:          "1",
    name:        "João Silva",
    description: "Concluiu a tarefa",
    date:        "2024-11-01",
    type:        "info",
  },
  { id:          "2",
    name:        "Ana Souza",
    description: "Faltou à aula",
    date:        "2024-11-02",
    type:        "warning",
 
  },
  { id:          "3",
    name:        "Carlos Oliveira",
    description: "Precisa melhorar as notas",
    date:        "2024-11-03",
    type:        "warning",
 
  },
  { id:          "4",
    name:        "Lucas Pereira",
    description: "Recebeu feedback positivo",
    date:        "2024-11-04",
    type:        "info",
  },
  { id:          "5",
    name:        "Mariana Gomes",
    description: "Faltou à prova final",
    date:        "2024-11-05",
    type:        "urgent",
  },
  { id:          "6",
    name:        "Fernando Costa",
    description: "Completou todos os exercícios",
    date:        "2024-11-06",
    type:        "info",
  },
  { id:          "7",
    name:        "Roberta Almeida",
    description: "Reprovado na avaliação final",
    date:        "2024-11-07",
    type:        "urgent",
  },
  { id:          "8",
    name:        "Pedro Lima",
    description: "Entrega de trabalho atrasada",
    date:        "2024-11-08",
    type:        "warning",
 
  },
  { id:          "9",
    name:        "Sofia Martins",
    description: "Fez melhorias no projeto",
    date:        "2024-11-09",
    type:        "info",
  },
  { id:          "10",
    name:        "Gustavo Rocha",
    description: "Precisa de mais atenção no conteúdo",
    date:        "2024-11-10",
    type:        "warning",
 
  },
  { id:          "11",
    name:        "Carla Souza",
    description: "Notificação sobre comportamento",
    date:        "2024-11-11",
    type:        "urgent",
  },
  { id:          "12",
    name:        "Ricardo Alves",
    description: "Fez um bom progresso na disciplina",
    date:        "2024-11-12",
    type:        "info",
  },
  { id:          "13",
    name:        "Daniela Ferreira",
    description: "Atrasou a entrega do relatório",
    date:        "2024-11-13",
    type:        "warning",
 
  },
  { id:          "14",
    name:        "Felipe Silva",
    description: "Foi elogiado pelo desempenho",
    date:        "2024-11-14",
    type:        "info",
  },
  { id:          "15",
    name:        "Juliana Costa",
    description: "Ficou de recuperação",
    date:        "2024-11-15",
    type:        "urgent",
  },
  { id:          "16",
    name:        "Rafael Pires",
    description: "Entregou trabalho com notas altas",
    date:        "2024-11-16",
    type:        "info",
  },
  { id:          "17",
    name:        "Tatiane Oliveira",
    description: "Desempenho abaixo da média",
    date:        "2024-11-17",
    type:        "warning",
 
  },
  { id:          "18",
    name:        "Bruna Lima",
    description: "Recuperação na disciplina de Matemática",
    date:        "2024-11-18",
    type:        "urgent",
  },
  { id:          "19",
    name:        "Igor Santos",
    description: "Fez uma excelente apresentação",
    date:        "2024-11-19",
    type:        "info",
  },
  { id:          "20",
    name:        "Marcos Duarte",
    description: "Não entregou o trabalho de grupo",
    date:        "2024-11-20",
    type:        "warning",
 
  },
];
